---
label_names:
  - georgia
  - wanda
  - iemon
  - boss
  - morinaga_milk
histograms:
  georgia: [0.05621033534407616, 0.09338168799877167, 0.02266545780003071, 0.01087941974401474, 0.04986400902271271, 0.24932003021240234, 0.20398911833763123, 0.06890299171209335, 0.040797825902700424, 0.0417044423520565, 0.16228467226028442, 0.0]
  wanda: [0.5755467414855957, 0.07852882891893387, 0.003976142965257168, 0.001988071482628584, 0.003976142965257168, 0.02087475173175335, 0.02982107363641262, 0.019880715757608414, 0.03677932545542717, 0.07952286303043365, 0.14910537004470825, 0.0]
  iemon: [0.004857737571001053, 0.17973630130290985, 0.6627342104911804, 0.07425399124622345, 0.02775850147008896, 0.01040943805128336, 0.0006939625018276274, 0.0, 0.0, 0.0, 0.0395558625459671, 0.0]
  boss: [0.1418861448764801, 0.3704333007335663, 0.06881903111934662, 0.022090058773756027, 0.01614273525774479, 0.05267629399895668, 0.05947323888540268, 0.02293967641890049, 0.030586237087845802, 0.034834325313568115, 0.18011894822120667, 0.0]
  morinaga_milk: [0.015002586878836155, 0.17847904562950134, 0.04086911678314209, 0.011381272226572037, 0.026901189237833023, 0.16140714287757874, 0.42783239483833313, 0.056389033794403076, 0.01914123073220253, 0.006207966711372137, 0.056389033794403076, 0.0]
