- direction: 'horizontal'
- name: 'force overwrite stand-coords'
  service: 'force_overwrite_stand_coords'
  image: "package://drc_task_common/icons/force-overwrite-stand-coords.png"
  image_size: [100, 100]
  column: 0
- name: 'auto overwrite stand-coords'
  service: 'auto_overwrite_stand_coords'
  image: "package://drc_task_common/icons/auto-overwrite-stand-coords.png"
  image_size: [100, 100]
  column: 0
  default_value: True
- name: 'no overwrite stand-coords'
  service: 'no_overwrite_stand_coords'
  image: "package://drc_task_common/icons/no-overwrite-stand-coords.png"
  image_size: [100, 100]
  column: 0
- name: 'enable head overwrite'
  service: 'enable_head_overwrite'
  image: "package://drc_task_common/icons/enable-head-overwrite.png"
  image_size: [100, 100]
  column: 1
- name: 'disable head overwrite'
  service: 'disable_head_overwrite'
  image: "package://drc_task_common/icons/disable-head-overwrite.png"
  image_size: [100, 100]
  column: 1
  default_value: True
- name: 'edge only'
  service: 'valve_edge_grasp_only'
  image: "package://drc_task_common/icons/valve-edge.png"
  image_size: [80, 80]
  column: 2
- name: 'edge preferred'
  service: 'valve_edge_grasp_preferred'
  image: "package://drc_task_common/icons/valve-edge.png"
  image_size: [80, 80]
  column: 2
  default_value: True
- name: 'center preferred'
  service: 'valve_center_grasp_preferred'
  image: "package://drc_task_common/icons/valve-center.png"
  image_size: [80, 80]
  column: 2
- name: 'center only'
  service: 'valve_center_grasp_only'
  image: "package://drc_task_common/icons/valve-center.png"
  image_size: [80, 80]
  column: 2
- name: 'push door'
  service: 'door_direction_push'
  image: "package://drc_task_common/icons/door-push.png"
  image_size: [100, 100]
  column: 3
  default_value: True
- name: 'pull door'
  service: 'door_direction_pull'
  image: "package://drc_task_common/icons/door-pull.png"
  image_size: [100, 100]
  column: 3
- name: 'force overwrite door arm'
  service: 'force_overwrite_door_arm'
  image: "package://drc_task_common/icons/force-overwrite-door-arm.png"
  image_size: [100, 100]
  column: 4
  default_value: True
- name: 'auto overwrite door arm'
  service: 'auto_overwrite_door_arm'
  image: "package://drc_task_common/icons/auto-overwrite-door-arm.png"
  image_size: [100, 100]
  column: 4
- name: 'drc-lasvegas'
  service: 'door_name_drc_lasvegas'
  column: 5
  default_value: True
- name: 'drc-lasvegas-mirror'
  service: 'door_name_drc_lasvegas_mirror'
  column: 5
- name: 'drc-sagami'
  service: 'door_name_drc_sagami'
  column: 5
- name: 'drc-sagami-mirror'
  service: 'door_name_drc_sagami_mirror'
  column: 5
- name: 'drc-box2'
  service: 'door_name_drc_box2'
  column: 5

- name: 'drill-rotate-zero'
  service: 'drill_rotate_zero'
  column: 6
- name: 'drill-rotate-one'
  service: 'drill_rotate_one'
  column: 6
- name: 'drill-rotate-two'
  service: 'drill_rotate_two'
  column: 6
  default_value: True
- name: 'drill-rotate-three'
  service: 'drill_rotate_three'
  column: 6